name: Build and Publish API & Frontend with Git SHA and Branch/Tag tags

on:
  push:
    branches: [master]
    tags: ["v*"]
    paths:
      - 'api/**'
      - 'frontend/**'
      - '.github/workflows/dockerhub-multi-publish.yml'


jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract metadata
        id: vars
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)
          REF_NAME=${GITHUB_REF_NAME}
          if [[ "$REF_NAME" == v* ]]; then
            VERSION_TAG="${REF_NAME:1}"
          else
            VERSION_TAG="$REF_NAME"
          fi
          echo "sha_short=$SHA_SHORT" >> $GITHUB_OUTPUT
          echo "ref_name=$REF_NAME" >> $GITHUB_OUTPUT
          echo "version_tag=$VERSION_TAG" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/api:${{ steps.vars.outputs.sha_short }}
            ${{ secrets.DOCKERHUB_USERNAME }}/api:${{ steps.vars.outputs.version_tag }}

  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract metadata
        id: vars
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)
          REF_NAME=${GITHUB_REF_NAME}
          if [[ "$REF_NAME" == v* ]]; then
            VERSION_TAG="${REF_NAME:1}"
          else
            VERSION_TAG="$REF_NAME"
          fi
          echo "sha_short=$SHA_SHORT" >> $GITHUB_OUTPUT
          echo "ref_name=$REF_NAME" >> $GITHUB_OUTPUT
          echo "version_tag=$VERSION_TAG" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ steps.vars.outputs.sha_short }}
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ steps.vars.outputs.version_tag }}
