name: Build and Publish API & Frontend

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
    paths:
      - 'api/**'
      - 'frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract version info
        id: vars
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)

          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION_TAG="${GITHUB_REF##refs/tags/v}"
          else
            VERSION_TAG=""
          fi

          echo "sha_short=$SHA_SHORT" >> $GITHUB_OUTPUT
          echo "version_tag=$VERSION_TAG" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push API (required tags)
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/api:${{ steps.vars.outputs.sha_short }}

      - name: Build and Push API (version tag)
        if: steps.vars.outputs.version_tag != ''
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api:${{ steps.vars.outputs.version_tag }}

      - name: Build and Push Frontend (required tags)
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ steps.vars.outputs.sha_short }}

      - name: Build and Push Frontend (version tag)
        if: steps.vars.outputs.version_tag != ''
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ steps.vars.outputs.version_tag }}

